spring:
  datasource:
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sport_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: a1b2c3d4

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.model
server:
  port: 9000